version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27019:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: app

  nodejs_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs_app
    restart: always
    ports:
      - "5000:5000"

volumes:
  mongodb_data:
    driver: local
